# Generated by Django 6.0.5 on 2026-09-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Model · Creator · Storyteller', max_length=120)),
                ('headline_line1', models.CharField(default='Beauty, style &', max_length=120)),
                ('headline_line2', models.CharField(default='the moments', max_length=120)),
                ('headline_emphasis', models.CharField(default='in between.', max_length=120)),
                ('intro_text', models.TextField(default='I create confident, feminine visuals rooted in beauty, fashion, lifestyle, and authentic storytelling.')),
                ('hero_image', models.ImageField(blank=True, upload_to='homepage/')),
                ('cta_text', models.CharField(default='Explore my work', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage content',
                'verbose_name_plural': 'Homepage content',
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('project_type', models.CharField(blank=True, max_length=120)),
                ('budget', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('category', models.CharField(choices=[('beauty', 'Beauty'), ('fashion', 'Fashion'), ('lifestyle', 'Lifestyle'), ('brand', 'Brand Content')], max_length=20)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('alt_text', models.CharField(blank=True, max_length=180)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
