# Generated by Django 6.0.5 on 2026-09-03 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='About Betra', max_length=120)),
                ('headline_line1', models.CharField(default='Confidence, creativity', max_length=160)),
                ('headline_emphasis', models.CharField(default='a little softness.', max_length=120)),
                ('intro_text', models.TextField(default='I care about the kind of content that feels beautiful but still personal — the kind that makes someone stop because it feels like a real moment, not just an ad.')),
                ('story_eyebrow', models.CharField(default='My story', max_length=120)),
                ('story_title', models.CharField(default="Hi, I'm Betra.", max_length=160)),
                ('story_paragraph_1', models.TextField(default="I'm a model and digital content creator with a love for beauty, fashion, lifestyle, and self-expression. Creating started as a way for me to share what I love, and it grew into a space where I can connect with people, work with brands, and tell stories visually.")),
                ('story_paragraph_2', models.TextField(default="My favorite content feels polished without feeling distant. I love clean beauty, feminine styling, everyday moments, and visuals that let personality come through. Whether I'm in front of a camera for a photoshoot or building a concept for a brand, I want the final piece to feel intentional and natural.")),
                ('story_paragraph_3', models.TextField(default='What matters most to me is creating from a place that still feels like me. I want my audience to trust what I share, and I want brands I work with to feel like their product has been introduced in a way that fits naturally into my world.')),
                ('story_image', models.ImageField(blank=True, upload_to='about/')),
                ('value_1_title', models.CharField(default='Authentic', max_length=80)),
                ('value_1_text', models.CharField(default='Content that keeps my real voice and personality at the center.', max_length=220)),
                ('value_2_title', models.CharField(default='Intentional', max_length=80)),
                ('value_2_text', models.CharField(default='Every detail — styling, framing, mood, and message — has a reason.', max_length=220)),
                ('value_3_title', models.CharField(default='Warm', max_length=80)),
                ('value_3_text', models.CharField(default='Beautiful visuals that still feel approachable, human, and easy to connect with.', max_length=220)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About page content',
                'verbose_name_plural': 'About page content',
            },
        ),
        migrations.CreateModel(
            name='ContactContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Say hello', max_length=120)),
                ('headline_line1', models.CharField(default="Let's stay", max_length=120)),
                ('headline_emphasis', models.CharField(default='connected.', max_length=120)),
                ('intro_text', models.TextField(default="For general questions, social messages, or anything that isn't a project inquiry, you can reach me here.")),
                ('section_eyebrow', models.CharField(default='Contact', max_length=120)),
                ('section_title_line1', models.CharField(default='Find me', max_length=120)),
                ('section_title_line2', models.CharField(default='around the internet.', max_length=120)),
                ('body_text', models.TextField(default='The easiest ways to reach me are by email or through my social platforms. For brand work, campaigns, UGC, modeling, or paid collaborations, use the dedicated inquiry page instead.')),
                ('general_email', models.EmailField(default='betraamare@icloud.com', max_length=254)),
                ('instagram_url', models.URLField(default='https://www.instagram.com/betra_amare')),
                ('instagram_handle', models.CharField(default='@betra_amare', max_length=80)),
                ('tiktok_url', models.URLField(default='https://www.tiktok.com/@betraamarey')),
                ('tiktok_handle', models.CharField(default='@betraamarey', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact page content',
                'verbose_name_plural': 'Contact page content',
            },
        ),
    ]
