# Generated by Django 6.0.5 on 2026-09-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_aboutcontent_contactcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='about_accent_image',
            field=models.ImageField(blank=True, upload_to='homepage/about/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_eyebrow',
            field=models.CharField(default='Meet Betra', max_length=120),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_main_image',
            field=models.ImageField(blank=True, upload_to='homepage/about/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_text_1',
            field=models.TextField(default="I'm Betra Amare, a model and digital creator with a love for beauty, fashion, confidence, and authentic storytelling. I create content that feels polished without losing the personality behind it."),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_text_2',
            field=models.TextField(default="Whether I'm creating for a brand or sharing a piece of my everyday life, I want the final result to feel warm, intentional, and true to me."),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_title_emphasis',
            field=models.CharField(default='Always myself.', max_length=120),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='about_title_line1',
            field=models.CharField(default='Creator first.', max_length=120),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='collab_body',
            field=models.TextField(default='I partner with beauty, fashion, lifestyle, and wellness brands to create content that feels natural to my audience while giving the product a beautiful, intentional spotlight.'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='collab_button_text',
            field=models.CharField(default='Work with me', max_length=80),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='collab_email',
            field=models.EmailField(default='workwithbetra@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='collab_eyebrow',
            field=models.CharField(default="Let's create something memorable", max_length=120),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='collab_title_emphasis',
            field=models.CharField(default='feel human.', max_length=120),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='collab_title_prefix',
            field=models.CharField(default='For brands that want content to', max_length=180),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='selected_eyebrow',
            field=models.CharField(default='Selected work', max_length=120),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='selected_title',
            field=models.CharField(default='A few favorites.', max_length=120),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='social_eyebrow',
            field=models.CharField(default='Follow along', max_length=120),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='social_title',
            field=models.CharField(default='More of the everyday.', max_length=120),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='world_body',
            field=models.TextField(default='From polished beauty looks to everyday lifestyle moments, I love creating imagery that feels personal, elevated, and easy to connect with.'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='world_eyebrow',
            field=models.CharField(default='A little bit of my world', max_length=120),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='world_title_emphasis',
            field=models.CharField(default='beautifully real.', max_length=120),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='world_title_line1',
            field=models.CharField(default='Created to feel', max_length=120),
        ),
    ]
