# Generated by Django 6.0.5 on 2026-09-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_homepagecontent_about_accent_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Work with Betra', max_length=120)),
                ('headline_line1', models.CharField(default="Let's create something", max_length=180)),
                ('headline_emphasis', models.CharField(default='worth remembering.', max_length=160)),
                ('intro_text', models.TextField(default="For paid partnerships, UGC, modeling, events, campaigns, or other creative projects, share the details below and I'll get back to you.")),
                ('section_eyebrow', models.CharField(default='Project inquiry', max_length=120)),
                ('section_title_line1', models.CharField(default='Tell me what', max_length=160)),
                ('section_title_line2', models.CharField(default='you have in mind.', max_length=160)),
                ('section_body', models.TextField(default='The more detail you can share about your brand, deliverables, timeline, usage, and budget, the easier it is for me to understand the fit.')),
                ('work_email', models.EmailField(default='workwithbetra@gmail.com', max_length=254)),
                ('button_text', models.CharField(default='Send inquiry', max_length=80)),
                ('success_message', models.CharField(default="Thank you! Your inquiry was sent successfully. I'll get back to you soon.", max_length=220)),
                ('form_note', models.CharField(default='Your inquiry will be securely saved so Betra can review it in the website admin.', max_length=220)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inquiry page content',
                'verbose_name_plural': 'Inquiry page content',
            },
        ),
        migrations.CreateModel(
            name='PortfolioPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Portfolio', max_length=120)),
                ('headline_line1', models.CharField(default='A collection of', max_length=160)),
                ('headline_emphasis', models.CharField(default='moments & moods.', max_length=160)),
                ('intro_text', models.TextField(default='Beauty, fashion, lifestyle, and brand storytelling — created with a soft editorial eye and a focus on personality.')),
                ('collab_eyebrow', models.CharField(default='Have something in mind?', max_length=120)),
                ('collab_title_prefix', models.CharField(default="Let's make something that feels", max_length=180)),
                ('collab_title_emphasis', models.CharField(default='like you.', max_length=120)),
                ('button_text', models.CharField(default='Start a project', max_length=80)),
                ('work_email', models.EmailField(default='workwithbetra@gmail.com', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio page content',
                'verbose_name_plural': 'Portfolio page content',
            },
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='category_1_image',
            field=models.ImageField(blank=True, default='', upload_to='homepage/categories/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='category_1_subtitle',
            field=models.CharField(default='Glow · Detail · Confidence', max_length=120),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='category_1_title',
            field=models.CharField(default='Beauty', max_length=80),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='category_2_image',
            field=models.ImageField(blank=True, default='', upload_to='homepage/categories/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='category_2_subtitle',
            field=models.CharField(default='Style · Editorial · Mood', max_length=120),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='category_2_title',
            field=models.CharField(default='Fashion', max_length=80),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='category_3_image',
            field=models.ImageField(blank=True, default='', upload_to='homepage/categories/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='category_3_subtitle',
            field=models.CharField(default='Everyday · Soft · Personal', max_length=120),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='category_3_title',
            field=models.CharField(default='Lifestyle', max_length=80),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='social_photo_1',
            field=models.ImageField(blank=True, default='', upload_to='homepage/social/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='social_photo_2',
            field=models.ImageField(blank=True, default='', upload_to='homepage/social/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='social_photo_3',
            field=models.ImageField(blank=True, default='', upload_to='homepage/social/'),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='social_photo_4',
            field=models.ImageField(blank=True, default='', upload_to='homepage/social/'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='link_url',
            field=models.URLField(blank=True, default='', help_text='Optional. Leave blank if the image should not open another page.'),
        ),
    ]
